"""views

Revision ID: 20b7e1d09462
Revises: 
Create Date: 2023-01-30 11:56:48.183482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20b7e1d09462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_name', sa.String(), nullable=False),
    sa.Column('subscription_type', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('subscription_description', sa.Text(), nullable=True),
    sa.Column('subscription_reminder', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_name')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(), nullable=True),
    sa.Column('profile_link', sa.String(), nullable=False),
    sa.Column('profile_bio', sa.Text(), nullable=True),
    sa.Column('profile_image_path', sa.String(), nullable=True),
    sa.Column('profile_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True, server_ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_link'),
    sa.UniqueConstraint('profile_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_name', sa.String(), nullable=False),
    sa.Column('link_url', sa.String(), nullable=False),
    sa.Column('link_tiny', sa.String(), nullable=False),
    sa.Column('link_thumbnail', sa.String(), nullable=True),
    sa.Column('link_enable', sa.Boolean(), nullable=False),
    sa.Column('link_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False, server_ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_tiny'),
    sa.UniqueConstraint('link_url')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_social', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False, server_ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewsresample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('view_location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('view_sampled_timestamp', sa.DateTime(), nullable=False),
    sa.Column('view_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False, server_ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clicksresample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('click_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('click_sampled_timestamp', sa.DateTime(), nullable=False),
    sa.Column('view_id', sa.Integer(), nullable=False, server_ondelete='CASCADE'),
    sa.Column('link_id', sa.Integer(), nullable=False, server_ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['viewsresample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clicksresample')
    op.drop_table('viewsresample')
    op.drop_table('setting')
    op.drop_table('link')
    op.drop_table('profile')
    op.drop_table('subscription')
    # ### end Alembic commands ###
