"""subscription

Revision ID: 32bd1497ada4
Revises: e126cca2cf19
Create Date: 2023-01-06 16:39:00.941972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bd1497ada4'
down_revision = 'e126cca2cf19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
