"""Including profilepicture trials

Revision ID: 66f6cd89bba6
Revises: 6c5075cb24bf
Create Date: 2022-12-28 18:34:54.916111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f6cd89bba6'
down_revision = '6c5075cb24bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
