"""Add sub to profile

Revision ID: 6775477b4e82
Revises: e495c591140d
Create Date: 2023-01-16 12:39:02.855673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6775477b4e82'
down_revision = 'e495c591140d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('subscription_id', sa.Integer(), nullable=True, server_ondelete='CASCADE'))
    op.create_foreign_key(None, 'profile', 'subscription', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'subscription_id')
    # ### end Alembic commands ###
