"""Included profile table

Revision ID: 6c5075cb24bf
Revises: 
Create Date: 2022-12-28 00:22:50.033098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5075cb24bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('profile_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('profile', sa.Column('profile_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'profile_updated')
    op.drop_column('profile', 'profile_created')
    # ### end Alembic commands ###
