"""view_migrations

Revision ID: 7efedf819a73
Revises: b1e9c8609157
Create Date: 2023-01-06 17:05:40.399335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efedf819a73'
down_revision = 'b1e9c8609157'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view', sa.Column('device_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view', 'device_name')
    # ### end Alembic commands ###
