"""view migrations test

Revision ID: b1e9c8609157
Revises: af2942f3c95a
Create Date: 2023-01-06 17:04:28.391450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e9c8609157'
down_revision = 'af2942f3c95a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
