"""Add sub to profile

Revision ID: e6ca496c3553
Revises: 0439a04baca4
Create Date: 2023-01-16 12:32:42.890799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ca496c3553'
down_revision = '0439a04baca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
