"""Changed table name

Revision ID: 01708c0c62aa
Revises: 2a9e02bf0c2b
Create Date: 2023-01-16 12:09:31.639566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01708c0c62aa'
down_revision = '2a9e02bf0c2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
