"""Changed table name

Revision ID: 2a9e02bf0c2b
Revises: 7efedf819a73
Create Date: 2023-01-16 12:01:46.085515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9e02bf0c2b'
down_revision = '7efedf819a73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
