"""subscription

Revision ID: bb9230bc2e41
Revises: a628caace08d
Create Date: 2023-01-06 16:42:56.617326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9230bc2e41'
down_revision = 'a628caace08d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
