"""subscription

Revision ID: df58c51f662d
Revises: bb9230bc2e41
Create Date: 2023-01-06 16:43:17.198725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df58c51f662d'
down_revision = 'bb9230bc2e41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('subscription_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'subscription_type')
    # ### end Alembic commands ###
