"""subscription

Revision ID: e126cca2cf19
Revises: 5d13cb0e7f59
Create Date: 2023-01-06 16:35:51.752344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e126cca2cf19'
down_revision = '5d13cb0e7f59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
