"""Add sub to profile

Revision ID: e495c591140d
Revises: e6ca496c3553
Create Date: 2023-01-16 12:36:22.592312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e495c591140d'
down_revision = 'e6ca496c3553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
